version: '3'

services:
  wordpress:
    image: wordpress:4.8.1-apache
    ports:
      - 8000:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    links: 
      - mysql
    environment: 
      WORDPRESS_DB_PASSWORD: wp


  mysql:
    image: mariadb:10.3.0
    ports:
      - 8081:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: wp